version: '2'
services:
  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
  kafka:
      image: wurstmeister/kafka:0.10.0.0
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_CREATE_TOPICS: "zup_kafka_string_topic:1:1,zup_kafka_object_topic:1:1,zup_kafka_object_invalid_topic:1:1,zup_kafka_list_string_topic:1:1,zup_kafka_list_object_topic:1:1"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - zookeeper
